services:
  api-publisher:
    build:
      context: ./PublisherApi
      dockerfile: Dockerfile
    container_name: ec2-publisher-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080

  api-consumer:
    build:
      context: ./ConsumerApi
      dockerfile: Dockerfile
    container_name: ec2-consumer-api
    environment:
      ASPNETCORE_URLS: http://+:8080
