name: MonoRepo - Deploy CloudFormation Stack

permissions:
  id-token: write
  contents: read
  
on:
  workflow_dispatch:
    inputs:
      stack_folder:
        description: "Stack Folders"
        required: true
        type: choice
        options:
          - aws-tutorial
          - ec2-docker
          - lambda

      stack_name:
        description: "Nome da CloudFormation Stack"
        required: true
        default: "study-stack"

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://${{ github.event.inputs.stack_folder }}/template.yml

      - name: Deploy stack
        run: |
          aws cloudformation deploy \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --template-file ${{ github.event.inputs.stack_folder }}/template.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Build Lambda
        run: |
          dotnet publish -c Release -o publish

      - name: Zip Lambda
        run: |
          cd publish
          zip -r ../lambda.zip .

      - name: Upload Lambda to S3
        run: |
          aws s3 cp lambda.zip \
            s3://lambda-artifacts-${{ secrets.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }}/lambda-${{ github.sha }}.zip

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name lambda-fn \
            --s3-bucket lambda-artifacts-${{ secrets.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }} \
            --s3-key lambda-${{ github.sha }}.zip


      - name: Dump CloudFormation events on failure
        if: failure()
        run: |
          echo "=== Stack status ==="
          aws cloudformation describe-stacks \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --query "Stacks[0].[StackStatus,StackStatusReason]" \
            --output table || true

          echo "=== Last stack events ==="
          aws cloudformation describe-stack-events \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --max-items 80 \
            --query "StackEvents[].[Timestamp,ResourceStatus,LogicalResourceId,ResourceType,ResourceStatusReason]" \
            --output table || true
