name: MonoRepo - Deploy CloudFormation Stack

permissions:
  id-token: write
  contents: read
  
on:
  workflow_dispatch:
    inputs:
      stack_folder:
        description: "Stack Folders"
        required: true
        type: choice
        options:
          - aws-tutorial
          - ec2-docker
          - lambda

      stack_name:
        description: "Nome da CloudFormation Stack"
        required: true
        default: "study-stack"

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get AWS Account ID
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - name: Deploy stack S3 Bucker
        run: |
          aws cloudformation deploy \
            --stack-name lambda-s3-stack \
            --template-file ${{ github.event.inputs.stack_folder }}/s3-stack.yml

      - name: Build Lambda
        run: |
          dotnet publish lambda/Lambda.csproj \
            -c Release \
            -o lambda/publish

      - name: Zip Lambda
        run: |
          cd lambda/publish
          zip -r ../../lambda.zip .

      - name: Upload Lambda to S3
        run: |
          aws s3 cp lambda.zip \
            s3://lambda-artifacts-${{ env.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }}/lambda-${{ github.sha }}.zip

      - name: Deploy stack
        run: |
          aws cloudformation deploy \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --template-file ${{ github.event.inputs.stack_folder }}/lambda-stack.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaS3Key=lambda-${{ github.sha }}.zip \
            --no-fail-on-empty-changeset

      - name: Dump CloudFormation events on failure
        if: failure()
        run: |
          echo "=== Stack status ==="
          aws cloudformation describe-stacks \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --query "Stacks[0].[StackStatus,StackStatusReason]" \
            --output table || true

          echo "=== Last stack events ==="
          aws cloudformation describe-stack-events \
            --stack-name ${{ github.event.inputs.stack_name }} \
            --max-items 80 \
            --query "StackEvents[].[Timestamp,ResourceStatus,LogicalResourceId,ResourceType,ResourceStatusReason]" \
            --output table || true
